version: '2'
services:

  publisher_app:
    build: containers/app/publisher
    container_name: publisher_app
    environment:
      RAILS_ENV: 'development'
    ports:
      - "3000:3000"
    volumes:
      - websub_sample_sync:/var/www:rw
    volumes_from:
      - datastore
      - bundle
    tty: true
    stdin_open: true

  subscriber_app:
    build: containers/app/subscriber
    container_name: subscriber_app
    environment:
      RAILS_ENV: 'development'
    ports:
      - "3001:3000"
    volumes:
      - websub_sample_sync:/var/www:rw
    volumes_from:
      - datastore
      - bundle
    tty: true
    stdin_open: true

  datastore:
    build: containers/datastore
    container_name: websub_sample_datastore
    volumes:
      - /datastore

  bundle:
    build: containers/bundle
    container_name: websub_sample_bundle
    volumes:
      - /bundle

# For docker-sync
volumes:
  websub_sample_sync:
    external: true
