version: '2'
services:

  publisher_app:
    build: containers/app/publisher
    container_name: publisher_app
    environment:
      RAILS_ENV: 'development'
    ports:
      - "3000:3000"
    volumes:
      - websub_sample_sync:/var/www:rw
    volumes_from:
      - datastore
      - bundle
    links:
      - db
      - redis
    tty: true
    stdin_open: true

  subscriber_app:
    build: containers/app/subscriber
    container_name: subscriber_app
    environment:
      RAILS_ENV: 'development'
    ports:
      - "3001:3000"
    volumes:
      - websub_sample_sync:/var/www:rw
    volumes_from:
      - datastore
      - bundle
    links:
      - db
      - redis
    tty: true
    stdin_open: true

  db:
    build: containers/mysql
    container_name: websub_sample_db
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'websub_sample_development'
      MYSQL_USER: 'websub_sample'
      MYSQL_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes_from:
      - datastore

  datastore:
    build: containers/datastore
    container_name: websub_sample_datastore
    volumes:
      - /datastore

  bundle:
    build: containers/bundle
    container_name: websub_sample_bundle
    volumes:
      - /bundle

  redis:
    image: redis:2.8.19
    container_name: websub_sample_redis
    ports:
      - '6379:6379'
    volumes_from:
      - datastore

# For docker-sync
volumes:
  websub_sample_sync:
    external: true
